// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<MobileResult> analyzeImageMobile({
  required List<int> imageBytes,
  required int k,
  int? maxDim,
  double? blurSigma,
}) => RustLib.instance.api.crateApiAnalyzeImageMobile(
  imageBytes: imageBytes,
  k: k,
  maxDim: maxDim,
  blurSigma: blurSigma,
);

class MobileColor {
  final String hex;
  final double percentage;
  final int red;
  final int green;
  final int blue;

  const MobileColor({
    required this.hex,
    required this.percentage,
    required this.red,
    required this.green,
    required this.blue,
  });

  @override
  int get hashCode =>
      hex.hashCode ^
      percentage.hashCode ^
      red.hashCode ^
      green.hashCode ^
      blue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileColor &&
          runtimeType == other.runtimeType &&
          hex == other.hex &&
          percentage == other.percentage &&
          red == other.red &&
          green == other.green &&
          blue == other.blue;
}

class MobileResult {
  final List<MobileColor> dominantColors;
  final int width;
  final int height;
  final Uint8List segmentationMap;

  const MobileResult({
    required this.dominantColors,
    required this.width,
    required this.height,
    required this.segmentationMap,
  });

  @override
  int get hashCode =>
      dominantColors.hashCode ^
      width.hashCode ^
      height.hashCode ^
      segmentationMap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileResult &&
          runtimeType == other.runtimeType &&
          dominantColors == other.dominantColors &&
          width == other.width &&
          height == other.height &&
          segmentationMap == other.segmentationMap;
}
