// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<ImageAnalysisResult> analyzeImageInMemory({
  required List<int> imageBytes,
}) => RustLib.instance.api.crateApiSimpleAnalyzeImageInMemory(
  imageBytes: imageBytes,
);

class ColorData {
  final String hex;
  final double percentage;

  const ColorData({required this.hex, required this.percentage});

  @override
  int get hashCode => hex.hashCode ^ percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorData &&
          runtimeType == other.runtimeType &&
          hex == other.hex &&
          percentage == other.percentage;
}

class ImageAnalysisResult {
  final List<ColorData> palette;
  final Uint32List pixelMap;
  final int width;
  final int height;

  const ImageAnalysisResult({
    required this.palette,
    required this.pixelMap,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      palette.hashCode ^ pixelMap.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageAnalysisResult &&
          runtimeType == other.runtimeType &&
          palette == other.palette &&
          pixelMap == other.pixelMap &&
          width == other.width &&
          height == other.height;
}
