// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<List<ColorData>> analyzeImageInMemory({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiSimpleAnalyzeImageInMemory(
      imageBytes: imageBytes,
    );

Future<RuleAnalysis> analyze603010Rule({required List<ColorData> palette}) =>
    RustLib.instance.api.crateApiSimpleAnalyze603010Rule(palette: palette);

class ColorData {
  final String hex;
  final double percentage;

  const ColorData({required this.hex, required this.percentage});

  @override
  int get hashCode => hex.hashCode ^ percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorData &&
          runtimeType == other.runtimeType &&
          hex == other.hex &&
          percentage == other.percentage;
}

class RuleAnalysis {
  final String dominantHex;
  final double dominantPercentage;
  final String secondaryHex;
  final double secondaryPercentage;
  final String accentHex;
  final double accentPercentage;
  final bool isBalanced;
  final String summary;

  const RuleAnalysis({
    required this.dominantHex,
    required this.dominantPercentage,
    required this.secondaryHex,
    required this.secondaryPercentage,
    required this.accentHex,
    required this.accentPercentage,
    required this.isBalanced,
    required this.summary,
  });

  @override
  int get hashCode =>
      dominantHex.hashCode ^
      dominantPercentage.hashCode ^
      secondaryHex.hashCode ^
      secondaryPercentage.hashCode ^
      accentHex.hashCode ^
      accentPercentage.hashCode ^
      isBalanced.hashCode ^
      summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleAnalysis &&
          runtimeType == other.runtimeType &&
          dominantHex == other.dominantHex &&
          dominantPercentage == other.dominantPercentage &&
          secondaryHex == other.secondaryHex &&
          secondaryPercentage == other.secondaryPercentage &&
          accentHex == other.accentHex &&
          accentPercentage == other.accentPercentage &&
          isBalanced == other.isBalanced &&
          summary == other.summary;
}
